services:
  telegram-bot:
    build: .
    container_name: telegram-tdl-forwarder
    restart: "no"
    volumes:
      - ./forward_history.json:/app/forward_history.json
      - /usr/local/bin/tdl:/usr/local/bin/tdl
      - ~/.tdl:/root/.tdl
    environment:
      - TZ=Asia/Shanghai  # 强制指定时区变量
      - API_ID=
      - API_HASH=
      - BOT_TOKEN=
      - ADMIN_IDS=
      - FORWARD_TO_CHAT_ID=
      - MONITOR_CHAT_IDS=源频道ID
      - USER_MONITOR_ENABLED=1
      - USER_SESSION_STRING=填入gen-session输出的字符串

  gen-session:
    build: .
    container_name: telegram-tdl-forwarder-gen-session
    profiles:
      - tools
    volumes:
      - ./gen_telethon_session.py:/app/gen_telethon_session.py
    environment:
      - TZ=Asia/Shanghai
      - API_ID=
      - API_HASH=
    command: python3 -u gen_telethon_session.py
    stdin_open: true
    tty: true
