services:
  telegram-bot:
    build: .
    container_name: telegram-tdl-forwarder
    restart: "no"
    volumes:
      - ./forward_history.json:/app/forward_history.json
      - /usr/local/bin/tdl:/usr/local/bin/tdl
      - ~/.tdl:/root/.tdl
    environment:
      - TZ=Asia/Shanghai  # 强制指定时区变量
      - API_ID=16612890
      - API_HASH=c0fc7dab1acc44f2a2da55cba248d656
      - BOT_TOKEN=7965940462:AAFCSi5PlG5xl9cqQDk6AFuZP4AT-K9OZQM
      - ADMIN_IDS=1227176277
      - FORWARD_TO_CHAT_ID=1234567890
      - MONITOR_CHAT_IDS=源频道ID
